language: java

jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk8
  - openjdk9

dist: trusty

env:
  global:
    - TMPDIR=/tmp

sudo: false

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

install: true

script:
  - ./build.sh gradle it
  - ./gradlew build jacocoTestReport

after_failure:
  - docker logs aergo.node

after_success:
  - ./gradlew alljacoco
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
  slack:
    rooms: blocko:LwABz6vDzniWNDuDgtYIeqrf
    on_success: change
    on_failure: always

