language: java

jdk:
  - openjdk8

sudo: false

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

env:
  global:
    - CODECOV_TOKEN="713e2a19-e591-42d1-bd24-872a8e497683"

script:
  - ./build.sh gradle

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
  slack:
    rooms: blocko:LwABz6vDzniWNDuDgtYIeqrf
    on_success: change
    on_failure: always

