title: heraj
logo: /assets/img/logo.png
description: Java Client for Aergo
baseurl: "/heraj"
url: "https://aergo.github.com"
show_downloads: false
google_analytics:
github:
  is_project_page: true
  owner_url: https://github.com/aergoio
  owner_name: aergo

markdown: kramdown
theme: jekyll-theme-minimal


